# AWS CodeBuild buildspec version; not app version
version: 0.2

env:
  variables:
    JENKINS_BUILDNUM: ""
  parameter-store:
    MAPP_RELEASE_KEYSTORE_PASSWORD: jenkins-apk-keystore-password
    MAPP_RELEASE_KEY_ALIAS: jenkins-apk-keystore-alias
    MAPP_RELEASE_KEY_PASSWORD: jenkins-apk-key-password
phases:
  pre_build:
    commands:
      - . ./aws-creds.sh
      - aws s3 ls --region us-west-2 s3://lo3energy-build/
      - aws s3 cp --region us-west-2 s3://lo3energy-build/upvoteparrot.gif .
